name: bemcs
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - pytest
  - addict
  - tqdm
  - h5py
  - colorcet
  - cmcrameri
  - rich
  - pandas
  - quadpy
  - shapely
  - geopandas
  - numba
  - pip
  - pip:
      - pygmsh
